# Background Project

**Background Project**

In this project, I created a self-service cashier system for a supermarket so customers can enter, update and delete the items purchased, the quantity and the price by themself.

**Goals**

Create a CRUD self-service cashier program according to the requested requirements (create an ID transaction, add items, update items, delete items, reset transaction, check order and check total shopping price)

# Demonstration

## Instructions

**Table of Product**

Item Name | Price |
--- | --- |
"vegetable oil"| Rp 30.000|
"rice"| Rp 20.000|
"egg"| Rp 25.000|
"soap"| Rp 11.000|
"shampoo"| Rp 16.000|
"tooth paste"| Rp 15.000|
"fried chicken"| Rp 20.000|

**Instruction to use Self Service Cashier**

1. Import the module
- Type: `import module_transaction as mt`

2. Create an instance
- Type: transaction_start1 = `mt.Transaction()`
- this action automatically create an id transaction.
  - To check id transaction, type: `transaction_start1.id_trx`

3. Add an Item
- Type: `transaction_start1.add_item("item name", "item quantity", "item price")`
- Note: Please type item name in all lower case

4. Update item name
- Type: `transaction_start1.update_name("current item name", "new item name")`

5. Update item price
- update price based on item name
- Type: `transaction_start1.update_price("item name", "correct price")`

6. Update item quantity
- update quantity based on item name
- Type: `transaction_start1.update_qty("item name", "correct quantity")`

7. Delete item
- delete an item based on item name
- Type: `transaction_start1.delete_item("item name")`

8. Reset transaction
- reset transaction will delete all transaction in its id transaction
- Type: `transaction_start1.reset()`

9. Check Order
- To check if the order is correct or not
- Type: `transaction_start1.check_order()`

10. Total Price
- To sum item price and quantity, also give discount if eligible
- Type: `transaction_start1.total_price()`

**Discount**
- If purchase more than Rp 500.000, get 10% discount
- If purchase more than Rp 300.000, get 8% discount
- If purchase more than Rp 200.000, get 5% discount

## Test Case

**Import Module and create object**

In [ ]:
# Import module_transaction
import module_transaction as mt

In [ ]:
# Create an object
transaction_123 = mt.Transaction()

In [ ]:
# Check id transaction
transaction_123.id_trx

'1_idtrx'

**Test 1**

A Customer wants to add 3 new items.
- Name: fried chicken, qty: 2, price: 20.000
- Name: toothpaste, qty: 2, price: 15.000
- Name: shampoo, qty: 1, price: 20.000

In [ ]:
# Add items
transaction_123.add_item("fried chicken", 2, 20_000)
transaction_123.add_item("toothpaste", 2, 15_000)
transaction_123.add_item("shampoo", 1, 20_000)

{1: ['fried chicken', 2, 20000]}
{1: ['fried chicken', 2, 20000], 2: ['toothpaste', 2, 15000]}
{1: ['fried chicken', 2, 20000], 2: ['toothpaste', 2, 15000], 3: ['shampoo', 1, 20000]}

**Test 2**

The Customer wants to delete `toothpaste` from its transaction.

In [ ]:
# Delete an item
transaction_123.delete_item("toothpaste")

{1: ['fried chicken', 2, 20000], 2: ['null data', 0, 0], 3: ['shampoo', 1, 20000]}

**Test 3**

The Customer wants to reset the transaction.

In [ ]:
# Reset transaction
transaction_123.reset()

Are you sure you want to delete all history?,                                     type ya/yes: ya
{}

**Test 4**

The Customer wants to make the same transaction in `Test 1` and check the order.

In [ ]:
# Add items
transaction_123.add_item("fried chicken", 2, 20_000)
transaction_123.add_item("toothpaste", 2, 15_000)
transaction_123.add_item("shampoo", 1, 20_000)

{4: ['fried chicken', 2, 20000]}
{4: ['fried chicken', 2, 20000], 5: ['toothpaste', 2, 15000]}
{4: ['fried chicken', 2, 20000], 5: ['toothpaste', 2, 15000], 6: ['shampoo', 1, 20000]}

In [ ]:
# Check order
transaction_123.check_order()

Item fried chicken is correct.
Item toothpaste has wrong name, please check again.
Item shampoo has wrong price, please check again.
       Item Name  Quantity Item  Price Item  sum_price
4  fried chicken              2       20000      40000
5     toothpaste              2       15000      30000
6        shampoo              1       20000      20000

**Test 5**

Update the wrong order from the `Test 4` result. Then, check again the order.

In [ ]:
# Update name
transaction_123.update_name('toothpaste', 'tooth paste')

{4: ['fried chicken', 2, 20000], 5: ['tooth paste', 2, 15000], 6: ['shampoo', 1, 20000]}

In [ ]:
# Update price
transaction_123.update_price('shampoo', 16000)

{4: ['fried chicken', 2, 20000], 5: ['tooth paste', 2, 15000], 6: ['shampoo', 1, 16000]}

In [ ]:
# Check order
transaction_123.check_order()

Item fried chicken is correct.
Item tooth paste is correct.
Item shampoo is correct.
       Item Name  Quantity Item  Price Item  sum_price
4  fried chicken              2       20000      40000
5    tooth paste              2       15000      30000
6        shampoo              1       16000      16000

**Test 6**

The customer has finished shopping. Calculate the total price of purchases.

In [ ]:
# Calculate total price
transaction_123.total_price()

You should pay Rp86,000.